### ISSUE TITLE
Error on Install in Shopware 5.6.7

### ISSUE THREAD

**Issue by kurcob84** [shopwareLabs/SwagMediaGCP#2]
On Install the Plugin in Shopware 5.6.7 I got the following error message:

Uncaught TypeError: Argument 3 passed to GuzzleHttp\Client::request() must be of the type array, string given, called in /homepages/13/d4295007264/htdocs/***/custom/plugins/SwagMediaGCP/vendor/guzzlehttp/guzzle/src/Client.php on line 87 and defined in /homepages/13/d4295007264/htdocs/***/custom/plugins/SwagMediaGCP/vendor/guzzlehttp/guzzle/src/Client.php:126 Stack trace: #0 /homepages/13/d4295007264/htdocs/***/custom/plugins/SwagMediaGCP/vendor/guzzlehttp/guzzle/src/Client.php(87): GuzzleHttp\Client->request('setDefaultOptio...', 'verify', '/homepages/13/d...') #1 /homepages/13/d4295007264/htdocs/***/engine/Shopware/Components/HttpClient/GuzzleFactory.php(41): GuzzleHttp\Client->__call('setDefaultOptio...', Array) #2 /homepages/13/d4295007264/htdocs/***/engine/Shopware/Components/HttpClient/GuzzleHttpClient.php(39): Shopware\Components\HttpClient\GuzzleFactory->createClient(Array) #3 /homepages/13/d4295007264/htdocs/***/var/cache/production_202005221

File:/ homepages/ 13/ d4295007264/ htdocs/ ****/ custom/ plugins/ SwagMediaGCP/ vendor/ guzzlehttp/ guzzle/ src/ Client.php

**Comment by kurcob84** [comment]
Only support to Shopware 5.5
